### ISSUE TITLE
A small mistake on pg 3

### ISSUE THREAD

**Issue by alperenevrin** [StatsWithR/figures#3]
I think there is a mistake on pg 3, the first equation. If there are _n_ data points, the first two expressions should be: 

![tex2img_1491235847](https://cloud.githubusercontent.com/assets/25860479/24618947/4801ed26-18a1-11e7-9c6e-cce82eac0484.png)

... part is just there to show the rest of the equation is the same.

Thanks.

**Comment by merliseclyde** [comment]
I think  the question is from the material at 
https://github.com/StatsWithR/figures/blob/master/04_bayesian_statistics/week_03/4.3.2_comparing_two_paired_means/Docs/4-3-2-pair-notes.pdf

If so, the likelihood  is broken down into two parts - one is the contribution from sampling distribution of the sample mean given the variance (which is why the power is just 1/2) and the second is from the distribution of the sample variance, which has the $\phi^{\nu/2}$ where $\nu = n-1$

Adding the two together we do get the term $\phi^{n/2}$.  If we used all of the raw data for formulating the likelihood, then we would need to start with $\phi^{n/2}$
